server:
  port: 8080

gateway:
  routes:
    - path: /api/users/**
      service: user-service
      targets:
      - url: http://localhost:8081
        weight: 100

    - path: /api/payments/**
      service: payment-service
      targets:
      - url: http://localhost:8082
        weight: 80
      - url: http://localhost:8083
        weight: 10
      - url: http://localhost:8084
        weight: 10

rate-limit:
  capacity: 100
  window-seconds: 60

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus